### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by styleshifter** [mydoge-com/wallet-translations#3]
Please add a file for DE and I will create the German translation.

**Comment by okerneb** [comment]
Hatte denselben Gedanken aber keine Ahnung von GitHub. Hab schon 'ne de.js inkl. Übersetzungen erstellt kannst gerne mal durchgucken.  :)
[de.zip](https://github.com/user-attachments/files/16163862/de.zip)

**Comment by alexanvl** [comment]
Please review and comment on the auto generated translations found in the PR https://github.com/mydoge-com/wallet-translations/pull/4

**Comment by styleshifter** [comment]
Ich habe jetzt auch angefangen, mir die Datei anzuschauen.

Am Mi., 10. Juli 2024 um 16:46 Uhr schrieb okerneb ***@***.***

**Comment by okerneb** [comment]
@styleshifter Hast du ‘ne Ahnung von dieser Codespace Geschichte? Hab gestern die Hälfte von der gegebenen Übersetzung formal also “per Sie” mit Korrekturen kommentiert da die gegebene Datei halt formal ist/war… Meine “Per du” Übersetzung hab ich heute früh angepasst und in diesem Codespace-Dings eingefügt und Commit/Pull-Request, keine Ahnung, was ich gemacht habe aber da ist was in der Warteschleife schätze/hoffe ich xDSolange da nichts passiert kann ich dir hier gerne die neue Datei posten ;)Am 11.07.2024 um 08:53 schrieb styleshifter ***@***.***>:﻿
Ich habe jetzt auch angefangen, mir die Datei anzuschauen.



Am Mi., 10. Juli 2024 um 16:46 Uhr schrieb okerneb ***@***.***

**Comment by okerneb** [comment]
@styleshifter I'll upload the new one now. See my next Comment there --> https://github.com/mydoge-com/wallet-translations/pull/4

**Comment by styleshifter** [comment]
I would suggest that we take the formal translation. We've put quite some effort in it already. The translations I did are formal as well.

**Comment by okerneb** [comment]
I see, but like Alex mentioned Doge is naturally very informal and I’d like it that way much more too.😅 So I spent the morning with this way and put together best of both to the newer informal one ;pI think the new informal version is complete and almost totally fine (Can’t tell because I can’t preview the app and a second look would not be wrong Oo) The given formal version has lot’s of mistakes. I had reviewed it up to Line 132 and need to look after the rest if we choose the formal way. Also I don’t know your formal version or is it that given one, I guess not, or?So @alexanvl we need a decision here, or more opinions XÐWe could also do both per language choice “Deutsch, per du” and “Deutsch, per Sie” or MyDoge could setup a choice to the user during initial setup and in the settings for formal/informal but then everything must be done twice (maybe) also for other languages.Von meinem iPhone gesendetAm 11.07.2024 um 10:09 schrieb styleshifter ***@***.***>:﻿
I would suggest that we take the formal translation. We've put quite some effort in it already. The translations I did are formal as well.

**Comment by styleshifter** [comment]
I'm fine with the informal version, too. I agree that we need to review it again in the app itself.

**Comment by okerneb** [comment]
Nice that we agree about this. So let’s move on informal. :)I’d suggest we wait for @alexanvl to take the newer informal version to GitHub before doing more review. If that’s fine after a 2nd look at it we’ll maybe see how it looks like in the app soon and can give further suggestions then. :bSent from my iPhoneOn Jul 11, 2024, at 11:24 AM, styleshifter ***@***.***> wrote:﻿
I'm fine with the informal version, too. I agree that we need to review it again in the app itself.
